<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Repository</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\InterfaceRepository\InterfaceRepository.csproj" />
      <ProjectReference Include="..\Logger\Logger.csproj" />
      <ProjectReference Include="..\UCore\UCore.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Dapper" Version="2.1.66" />
      <PackageReference Include="Dapper.SqlBuilder" Version="2.1.66" />
      <PackageReference Include="Eka.Dapper.Json" Version="1.1.0" />
      <PackageReference Include="FluentMigrator" Version="7.1.0" />
      <PackageReference Include="FluentMigrator.Runner" Version="7.1.0" />
      <PackageReference Include="FluentMigrator.Runner.SqlServer" Version="7.1.0" />
      <PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.3.9" />
      <PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.9" />
      <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="9.0.9" />
      <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.9" />
      <PackageReference Include="System.Data.SqlClient" Version="4.9.0" />
    </ItemGroup>

</Project>
