<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\ApiTelegramBot\ApiTelegramBot.csproj" />
      <ProjectReference Include="..\EFRepository\EFRepository.csproj" />
      <ProjectReference Include="..\Logger\Logger.csproj" />
      <ProjectReference Include="..\DapperRepository\DapperRepository.csproj" />
      <ProjectReference Include="..\UCore\UCore.csproj" />
      <ProjectReference Include="..\UJob\UJob.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Cronos" Version="0.11.1" />
      <PackageReference Include="Dadata" Version="25.7.0" />
      <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.0" />
      <PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.9" />
      <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="9.0.9" />
      <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.9" />
      <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="9.0.9" />
      <PackageReference Include="MiniProfiler" Version="4.5.4" />
      <PackageReference Include="MiniProfiler.AspNetCore" Version="4.5.4" />
      <PackageReference Include="MiniProfiler.AspNetCore.Mvc" Version="4.5.4" />
      <PackageReference Include="MiniProfiler.EntityFrameworkCore" Version="4.5.4" />
      <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
      <PackageReference Include="System.Linq.Dynamic.Core" Version="1.7.2" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="PolicyForMinimalAPI\" />
    </ItemGroup>

</Project>
