<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\InterfaceRepository\InterfaceRepository.csproj" />
      <ProjectReference Include="..\Logger\Logger.csproj" />
      <ProjectReference Include="..\DapperRepository\DapperRepository.csproj" />
      <ProjectReference Include="..\UCore\UCore.csproj" />
      <ProjectReference Include="..\UJob\UJob.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="BitMiracle.Docotic.Pdf.HtmlToPdf" Version="9.8.19414-dev" />
      <PackageReference Include="Microsoft.AspNetCore.App" Version="2.2.8" />
      <PackageReference Include="Select.HtmlToPdf.NetCore" Version="25.2.0" />
      <PackageReference Include="Telegram.Bot" Version="22.7.5" />
    </ItemGroup>

</Project>
